import "./globals.css";
import { Header, Footer } from "@/components";

import CursorContextProvider from "../components/cursourAnimation/cursorContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CursorContextProvider>
          <Header />
          {children}
          <Footer />
        </CursorContextProvider>
      </body>
    </html>
  );
}
