import "./globals.css";
import { source_code_pro } from "./fonts";
import { Header, Footer } from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={source_code_pro.className}>
        <Header />
        {children} 
        <Footer />
      </body>
    </html>
  );
}
